# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artykuly',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tytul', models.CharField(max_length=255)),
                ('wersja_krotka', models.TextField(blank=True, null=True)),
                ('wersja_dluga', models.TextField(blank=True, null=True)),
                ('autor', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('slot1', models.CharField(blank=True, max_length=255, null=True)),
                ('slot2', models.CharField(blank=True, max_length=255, null=True)),
                ('slot3', models.CharField(blank=True, max_length=255, null=True)),
                ('slot4', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'artykuly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(blank=True, max_length=250, null=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('slot1', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'kategorie',
                'managed': False,
            },
        ),
    ]
